djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
path('admin/', admin.site.urls),
path("", include("dogs.urls", namespace="dogs"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogs/urls.py
from django.urls import path
from dogs.views import index, BreedView, DogView, DogCreateView, DogDetailView, DogUpdateView, DogDeleteView
from dogs.apps import DogsConfig

app_name = DogsConfig.name

urlpatterns = [
    path("", index, name="index"),
    path("breeds/", BreedView.as_view(), name="breeds"),
    path("dogs/<int:pk>/", DogView.as_view(), name="dogs_breeds"),
    path("dogs/view/<int:pk>/", DogDetailView.as_view(), name="dogs_view"),
    path("dogs/create/", DogCreateView.as_view(), name="dogs_create"),
    path("dogs/update/<int:pk>/", DogUpdateView.as_view(), name="dogs_update"),
    path("dogs/delete/<int:pk>/", DogDeleteView.as_view(), name="dogs_delete"),
]

dogs/models.py
from django.db import models

NULLABLE = {"blank": True, "null": True}


class Breed(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название")
    description = models.TextField(verbose_name="Описание")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Порода"
        verbose_name_plural = "Породы"


class Dog(models.Model):
    name = models.CharField(max_length=100, verbose_name="Кличка")
    breed = models.ForeignKey(Breed, on_delete=models.SET_NULL, **NULLABLE, verbose_name="Порода")
    photo = models.ImageField(upload_to="dogs/", **NULLABLE, verbose_name="Фото")
    birth_day = models.DateField(**NULLABLE, verbose_name="Дата рождения")

    def __str__(self):
        return f"{self.name} {self.breed}"

    class Meta:
        verbose_name = "Собака"
        verbose_name_plural = "Собаки"

dogs/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from dogs.models import Dog, Breed


def index(request):
    context = {
        "object_list": Breed.objects.all()[:3]
    }
    return render(request, "dogs/breed_list.html", context)


class BreedView(ListView):
    model = Breed


class DogView(ListView):
    model = Dog

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(breed__pk=self.kwargs.get("pk"))
        return queryset


class DogDetailView(DetailView):
    model = Dog


class DogCreateView(CreateView):
    model = Dog
    fields = ("name", "breed", "photo")
    success_url = reverse_lazy("dogs:breeds")


class DogUpdateView(UpdateView):
    model = Dog
    fields = ("name", "breed", "photo", "birth_day")

    def get_success_url(self):
        return reverse("dogs:dogs_breeds", args=[self.object.breed.pk])


class DogDeleteView(DeleteView):
    model = Dog

    def get_success_url(self):
        return reverse("dogs:dogs_breeds", args=[self.object.breed.pk])

dogs/templates/dogs/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <title>Питомник</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/album/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">About</h4>
                    <p class="text-muted">Данный сайт представляет собой питомник с информацией о собаках</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Contact</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url "dogs:index" %}" class="text-white">Главная</a></li>
                        <li><a href="{% url "dogs:breeds" %}" class="text-white">Породы</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Питомник</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Питомник</h1>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}

        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting
            started guide</a>.</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

dogs/templates/dogs/breed_list.html
{% extends "dogs/base.html" %}

{% block content %}
    <div class="row">
        {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p class="card-text">{{object.name}}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url "dogs:dogs_breeds" object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">К собакам</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

dogs/templates/dogs/dog_confirm_delete.html
{% extends "dogs/base.html" %}
{% block content %}
    <div class="col-12">
         <div class="row">
             <div class="col-6">
                 <div class="card">
                     <form method="post">
                         {%  csrf_token %}
                         {{form.as_p}}
                         <p>Действительно хотите удалить?</p>
                         <button type="submit" class="btn btn-outline-danger">Удалить</button>
                         <a href="{% url "dogs:dogs_breeds" object.pk %}" class="btn btn-outline-warning">Отмена</a>
                     </form>
                 </div>
             </div>
         </div>
    </div>
{% endblock %}

dogs/templates/dogs/dog_detail.html
{% extends "dogs/base.html" %}
{% load my_tags %}
{% block content %}
    <div class="row">
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{{object.photo|mymedia}}"
                     alt="Card image cap">
                <div class="card-body">
                    <p class="card-text">Имя: {{object.name}}</p>
                    <p class="card-text">Порода: {{object.breed.name}}</p>
                    <p class="card-text">{{object.breed.description}}</p>
                    <span class="text-muted">{{object.birth_day|default:"---"}}</span>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

dogs/templates/dogs/dog_form.html
{% extends "dogs/base.html" %}
{% block content %}
    <div class="col-12">
         <div class="row">
             <div class="col-6">
                 <div class="card">
                     <form method="post">
                         {%  csrf_token %}
                         {{form.as_p}}
                         <button type="submit" class="btn btn-primary">Создать</button>
                     </form>
                 </div>
             </div>
         </div>
    </div>
{% endblock %}

dogs/templates/dogs/dog_list.html
{% extends "dogs/base.html" %}
{% load my_tags %}

{% block content %}
    <div class="row">
        <div class="col-12 mb-5">
            <a href="{% url "dogs:dogs_create" %}" class="btn btn-primary">Добавить собаку</a>
        </div>
        {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{{object.photo|mymedia}}"
                     alt="Card image cap">
                <div class="card-body">
                    <p class="card-text">{{object.name|title}}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url "dogs:dogs_view" object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Просмотр</a>
                            <a href="{% url "dogs:dogs_update" object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Изменить</a>
                            <a href="{% url "dogs:dogs_delete" object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

dogs/templates/dogs/dogs.html
{% extends "dogs/base.html" %}
{% load my_tags %}

{% block content %}
    <div class="row">
        {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{{object.photo|mymedia}}"
                     alt="Card image cap">
                <div class="card-body">
                    <p class="card-text">{{object.name|title}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

dogs/templates/dogs/index.html
{% extends "dogs/base.html" %}

{% block content %}
    <div class="row">
        {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p class="card-text">{{object.name}}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url "dogs:dogs_breeds" object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">К собакам</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}